services:
  - type: web
    name: collage-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
